### ISSUE TITLE
The remote server returned an error: (404) Not Found

### ISSUE THREAD

**Issue by zimorodokan** [kerams/memrise-scraper#2]
Hi!
I have tried to get https://www.memrise.com/course/2190187/angliiskii-1/
But I couldn't.
I tried MemriseScraper.exe 2190187/angliiskii-1 and MemriseScraper.exe 2190187

d:\Software\Anki\MemriseScraper>MemriseScraper 20190187

Unhandled Exception: System.Net.WebException: The remote server returned an error: (404) Not Found.
Response from https://www.memrise.com/course/20190187/:
<!doctype html>

 <html lang="en"> 

d:\Software\Anki\MemriseScraper>MemriseScraper.exe 2190187/angliiskii-1
...............
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
Response from https://www.memrise.com/api/thing/get/?thing_id=2000001225:
Not found ---> System.Net.WebException: The remote server returned an error: (404) Not Found.

**Comment by kerams** [comment]
>d:\Software\Anki\MemriseScraper>MemriseScraper 20190187

It's 219, not 2019 :)

**Comment by zimorodokan** [comment]
Yes, but it's not working too
d:\Software\Anki\MemriseScraper>MemriseScraper.exe 2190187
...............
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
Response from https://www.memrise.com/api/thing/get/?thing_id=2000001227:
Not found ---> System.Net.WebException: The remote server returned an error: (404) Not Found.

**Comment by kerams** [comment]
There must be something wrong with this specific course, like an incomplete word or something. I'll take a look.

**Comment by kerams** [comment]
Here, this will work for you https://github.com/kerams/memrise-scraper/releases/tag/v1.0.3

The problem was this gammar level https://www.memrise.com/course/2190187/angliiskii-1/4/. It'll now skip these because I'm not sure they have all the required data anyway.

**Comment by zimorodokan** [comment]
Thank you very much :)
