### ISSUE TITLE
The remote server returned an error: (404) Not Found.

### ISSUE THREAD

**Issue by firenze998** [kerams/memrise-scraper#3]
Hi, v.1.0.3. doesn't work anymore.

C:\Users\Ftp\Downloads\MemriseScraper\MemriseScraper.exe 418254
..................
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.

<details>
  <summary>Click to expand</summary><p>
Response from https://www.memrise.com/api/thing/get?thing_id=41265960:
<!doctype html><html class="no-js" lang="en"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="author" content="Memrise">
    <meta name="description" content="">
    <meta name="generator" content="HubSpot">
    <title></title>
    <link rel="shortcut icon" href="https://www.memrise.com/hubfs/memrise-flavicon.png">

    <meta property="og:description" content="">
    <meta property="og:title" content="">
    <meta name="twitter:description" content="">
    <meta name="twitter:title" content="">

    <style>
a.cta_button{-moz-box-sizing:content-box !important;-webkit-box-sizing:content-box !important;box-sizing:content-box !important;vertical-align:middle}.hs-breadcrumb-menu{list-style-type:none;margin:0px 0px 0px 0px;padding:0px 0px 0px 0px}.hs-breadcrumb-menu-item{float:left;padding:10px 0px 10px 10px}.hs-breadcrumb-menu-divider:before{content:'>';padding-left:10px}.hs-featured-image-link{border:0}.hs-featured-image{float:right;margin:0 0 20px 20px;max-width:50%}@media (max-width: 568px){.hs-featured-image{float:none;margin:0;width:100%;max-width:100%}}.hs-screen-reader-text{clip:rect(1px, 1px, 1px, 1px);height:1px;overflow:hidden;position:absolute !important;width:1px}
</style>

<link rel="stylesheet" href="https://www.memrise.com/hs-fs/hub/6968579/hub_generated/template_assets/31539912616/1603108403845/Memrise_Website_July_2020/Coded_Files/style.min.css">

<style>

.language__switcher-other{ display:none;}
.language__switcher:hover .language__switcher-other { display: flex; }
span.language__switcher-current { cursor: pointer;}
</style>

<link rel="stylesheet" href="https://www.memrise.com/hs-fs/hub/6968579/hub_generated/module_assets/32625371464/1599567352136/module_32625371464_404_-_Hero_Module.min.css">

<style>
  .hero-section:before{background:url('https://www.memrise.com/hubfs/Memrise%20July%202020/Images/Left%20image-2.png')}
  .hero-section:after{background:url('https://www.memrise.com/hubfs/Memrise%20July%202020/Images/Right%20image-2.png')}
</style>

    <link rel="canonical" href="https://www.memrise.com/404">

<meta name="viewport" content="width=device-width, initial-scale=1">
<script>
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware"];analytics.factory=function(e){return function(){var t=Array.prototype.slice.call(arguments);t.unshift(e);analytics.push(t);return analytics}};for(var e=0;e<analytics.methods.length;e++){var t=analytics.methods[e];analytics[t]=analytics.factory(t)}analytics.load=function(e,t){var n=document.createElement("script");n.type="text/javascript";n.async=!0;n.src="https://cdn.segment.com/analytics.js/v1/"+e+"/analytics.min.js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(n,a);analytics._loadOptions=t};analytics.SNIPPET_VERSION="4.1.0";
  analytics.load("xvSSMvt1DM5rAVWladuKUnzUp0gsLrTg");
  analytics.page();
  }}();
</script>

<script data-ad-client="ca-pub-4000617293200543" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<meta property="og:url" content="https://www.memrise.com/404">
<meta name="twitter:card" content="summary">
<meta http-equiv="content-language" content="en">
<link rel="stylesheet" href="//cdn2.hubspot.net/hub/-1/hub_generated/template_assets/1495141902003/hubspot_default/shared/responsive/layout.min.css">

</head>
<body class="   hs-content-id-0 hs-site-page page " style="">
    <div class="header-container-wrapper">
    <div class="header-container container-fluid">

<div class="row-fluid-wrapper row-depth-1 row-number-1 ">
<div class="row-fluid ">
<div class="span12 widget-span widget-type-custom_widget " style="" data-widget-type="custom_widget" data-x="0" data-w="12">
<div id="hs_cos_wrapper_module_1595326731320354" class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module" style="" data-hs-cos-general-type="widget" data-hs-cos-type="module"><div class="wrapper-header">

  <div class="container">

    <div class="inner-header">
      <div class="logo">
        <a class="showin" href="/" title="Home">
          <img src="https://www.memrise.com/hubfs/Memrise%20July%202020/Images/logo.png" alt="memrise">
        </a>
        <a class="hidein returnTopAction" href="#"> Back to top <i class="fas fa-arrow-up"></i></a>
      </div>
      <div class="menu custom-menu-primary">
        <span id="hs_cos_wrapper_module_1595326731320354_" class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_menu" style="" data-hs-cos-general-type="widget" data-hs-cos-type="menu"><div id="hs_menu_wrapper_module_1595326731320354_" class="hs-menu-wrapper active-branch flyouts hs-menu-flow-horizontal" role="navigation" data-sitemap-name="default" data-menu-id="33852855951" aria-label="Navigation Menu">
 <ul>
  <li class="hs-menu-item hs-menu-depth-1"><a href="https://www.memrise.com/languages-online" role="menuitem">Courses</a></li>
 </ul>
</div></span>
      </div>
      <div class="menu-right">
        <span id="hs_cos_wrapper_module_1595326731320354_" class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_simple_menu" style="" data-hs-cos-general-type="widget" data-hs-cos-type="simple_menu"><div id="hs_menu_wrapper_module_1595326731320354_" class="hs-menu-wrapper active-branch flyouts hs-menu-flow-horizontal" role="navigation" data-sitemap-name="" data-menu-id="" aria-label="Navigation Menu">
 <ul>
  <li class="hs-menu-item hs-menu-depth-1"><a href="https://app.memrise.com/signin" role="menuitem" target="_self">Login</a></li>
  <li class="hs-menu-item hs-menu-depth-1"><a href="https://www.memrise.com/bienvenue" role="menuitem" target="_self">Sign up</a></li>
 </ul>
</div></span>
      </div>
      <div class="header-nav-right dis-flex vmiddle">

        <div class="language-switcher">

          <div class="footer-language global-icon dis-flex">
            <p>
              Select language <i class="fa fa-caret-down"></i>

              <img src="https://www.memrise.com/hubfs/Memrise%20July%202020/Images/en.png" alt="en">

            </p>

          </div>
          <div style="display:none;">
            <span id="hs_cos_wrapper_module_1595326731320354_language_switcher" class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_language_switcher" style="" data-hs-cos-general-type="widget" data-hs-cos-type="language_switcher"></span>
          </div>
     <ul class="language language__switcher-other"></ul>

        </div>
      </div>
    </div>
  </div>
</div>

</div>

</div>
</div>
</div>

    </div>
</div>

<div class="body-container-wrapper">
    <div class="body-container container-fluid">

<div class="row-fluid-wrapper row-depth-1 row-number-1 ">
<div class="row-fluid ">
<div class="span12 widget-span widget-type-custom_widget " style="" data-widget-type="custom_widget" data-x="0" data-w="12">
<div id="hs_cos_wrapper_module_1595326802211360" class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module" style="" data-hs-cos-general-type="widget" data-hs-cos-type="module"><div class="hero-section before after hero-center bg relative" style="background:#ffffff">
  <div class="container">

      <div class="hero-cen relative w-100 white">
           <h1> 404 error </h1>
        <h4>We can't seem to find the page you're looking for</h4>
<p>&nbsp;</p>

        <div class="common-cta">

          <a href="https://www.memrise.com">
            Return to homepage
          </a>
        </div>

      </div>

  </div>

</div>

</div>

</div>
</div>
</div>

    </div>
</div>

<div class="footer-container-wrapper">
    <div class="footer-container container-fluid">

<div class="row-fluid-wrapper row-depth-1 row-number-1 ">
<div class="row-fluid ">
<div class="span12 widget-span widget-type-custom_widget " style="" data-widget-type="custom_widget" data-x="0" data-w="12">
<div id="hs_cos_wrapper_module_1595326733426356" class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_module" style="" data-hs-cos-general-type="widget" data-hs-cos-type="module">
<footer>

  <div class="container">
    <div class="f-logo">
      <a href="/">
        <img src="https://www.memrise.com/hubfs/Memrise%20July%202020/Images/logo.png" alt="memrise">
      </a>
    </div>
    <div class="common-link">

      <a class="com-link" href="https://app.memrise.com/bienvenue">
        Start Learning
      </a>

    </div>
    <div class="f-social-icons">
      <a class="footer-social-link" href="https://www.facebook.com/memrise" target="_blank" rel="noopener"> <img src="https://www.memrise.com/hubfs/Memrise%20July%202020/Images/facebook-92317b7cfd13.svg" alt="Facebook-logo"> </a> <a class="footer-social-link" href="https://twitter.com/memrise" target="_blank" rel="noopener"> <img src="https://www.memrise.com/hubfs/Memrise%20July%202020/Images/twitter-2ca5e163d013.svg" alt="Twitter-logo"> </a> <a class="footer-social-link" href="https://www.youtube.com/channel/UC4Ywz0GYzq7nlPtKCMQ8m0w" target="_blank" rel="noopener"> <img src="https://www.memrise.com/hubfs/Memrise%20July%202020/Images/youtube-41dd4e237d13.svg" alt="Youtube-Logo"> </a> <a class="footer-social-link" href="https://www.instagram.com/memrise" target="_blank" rel="noopener"> <img src="https://www.memrise.com/hubfs/Memrise%20July%202020/Images/instagram-8842365eb713.svg" alt="Instagram-logo"> </a>
    </div>
    <div class="footer-top">
      <div class="">
        <div class="footer-top-left">
          <span id="hs_cos_wrapper_module_1595326733426356_" class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_menu" style="" data-hs-cos-general-type="widget" data-hs-cos-type="menu"><div id="hs_menu_wrapper_module_1595326733426356_" class="hs-menu-wrapper active-branch flyouts hs-menu-flow-horizontal" role="navigation" data-sitemap-name="default" data-menu-id="31819396830" aria-label="Navigation Menu">
 <ul>
  <li class="hs-menu-item hs-menu-depth-1"><a href="https://www.memrise.com/about" role="menuitem">About Us</a></li>
  <li class="hs-menu-item hs-menu-depth-1"><a href="https://www.memrise.com/press" role="menuitem">Press</a></li>
  <li class="hs-menu-item hs-menu-depth-1"><a href="https://blog.memrise.com/" role="menuitem">Memrise Blog</a></li>
  <li class="hs-menu-item hs-menu-depth-1"><a href="https://www.memrise.com/team" role="menuitem">Team</a></li>
  <li class="hs-menu-item hs-menu-depth-1"><a href="https://www.memrise.com/contact" role="menuitem">Contact Us</a></li>
  <li class="hs-menu-item hs-menu-depth-1"><a href="https://engineering.memrise.com/" role="menuitem">Engineering Blog</a></li>
  <li class="hs-menu-item hs-menu-depth-1"><a href="https://www.memrise.com/jobs" role="menuitem">Jobs</a></li>
  <li class="hs-menu-item hs-menu-depth-1"><a href="https://memrise.helpshift.com/a/memrise-learn-a-new-language/?p=web" role="menuitem">FAQ &amp; Help</a></li>
  <li class="hs-menu-item hs-menu-depth-1"><a href="https://community.memrise.com/" role="menuitem">Forums</a></li>
  <li class="hs-menu-item hs-menu-depth-1"><a href="https://www.memrise.com/dictionary/french" role="menuitem">French Phrasebook</a></li>
  <li class="hs-menu-item hs-menu-depth-1"><a href="https://www.memrise.com/dictionary/spanish" role="menuitem">Spanish Phrasebook</a></li>
  <li class="hs-menu-item hs-menu-depth-1"><a href="https://www.memrise.com/dictionary" role="menuitem">Phrasebooks</a></li>
 </ul>
</div></span>
        </div>
        <div class="footer-com-links dis-flex">
          <a class="footer-link" href="https://www.memrise.com/terms" rel=" noopener">Terms of Use</a> <a class="footer-link" href="https://www.memrise.com/privacy" rel=" noopener">Privacy Policy</a> <a class="footer-link" href="https://www.memrise.com/cookies" rel=" noopener">Cookie Policy</a>
        </div>
      </div>
    </div>
  </div>

</footer>

</div>

</div>
</div>
</div>

    </div>
</div>

    <script src="/hs/hsstatic/jquery-libs/static-1.1/jquery/jquery-1.7.1.js"></script>
<script>hsjQuery = window['jQuery'];</script>
<script>
(function () {
    window.addEventListener('load', function () {
        setTimeout(function () {
            var xhr = new XMLHttpRequest();
            xhr.open('POST', '/_hcms/perf', true /*async*/);
            xhr.setRequestHeader("Content-type", "application/json");
            xhr.onreadystatechange = function () {
                // do nothing.
            };
            var connection = navigator.connection || navigator.mozConnection || navigator.webkitConnection;
            function populateNetworkInfo(name, connection, info) {
                if (name in connection) {
                    info[name] = connection[name];
                }
            }
            var networkInfo = {};
            if (connection) {
                ['type', 'effectiveType', 'downlink', 'rtt'].forEach(function(name) {
                    populateNetworkInfo(name, connection, networkInfo);
                });
            }
            var perfData = {
                url: location.href,
                portal: 6968579,
                content: -1,
                group: -1,
                connection: networkInfo,
                timing: performance.timing
            };
            xhr.send(JSON.stringify(perfData));
        }, 3000);  // Execute this 3 seconds after onload.
    });
})();
</script>

<script>
if (typeof hsVars !== 'undefined') { hsVars['language'] = 'en'; }
</script>

<script src="/hs/hsstatic/cos-i18n/static-1.27/bundles/project.js"></script>
<script src="https://www.memrise.com/hs-fs/hub/6968579/hub_generated/module_assets/31539806945/1602569029957/module_31539806945_Header_July_2020.min.js"></script>
<script src="/hs/hsstatic/keyboard-accessible-menu-flyouts/static-1.17/bundles/project.js"></script>

<script>
if(document.querySelector(".lang_list_class")){
  document.querySelector(".language__switcher-other").innerHTML = document.querySelector(".lang_list_class").innerHTML;
} else {
  document.querySelector(".language-switcher").style.display = 'none';
}
$(".language__switcher-other a[data-language='zh-hans']").text('????')
$(".language__switcher-other a[data-language='zh-hant']").text('????')
$(".language__switcher-other a[data-language='tr']").text('Turkce')

</script>

<script src="https://www.memrise.com/hs-fs/hub/6968579/hub_generated/template_assets/31540438481/1602568208497/Memrise_Website_July_2020/Coded_Files/common.min.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
<script>
  WebFont.load({
    google: {
      families: ['Open Sans']
    }
  });
</script>

<script type="text/javascript">
var _hsq = _hsq || [];
_hsq.push(["setContentType", "standard-page"]);
_hsq.push(["setCanonicalUrl", "https:\/\/www.memrise.com\/404"]);
_hsq.push(["setPageId", ""]);
_hsq.push(["setContentMetadata", {
    "contentPageId": null,
    "legacyPageId": null,
    "contentFolderId": null,
    "contentGroupId": null,
    "abTestId": null,
    "languageVariantId": null,
    "languageCode": "en",

}]);
</script>

<script type="text/javascript" id="hs-script-loader" async defer src="/hs/scriptloader/6968579.js"></script>

<script type="text/javascript">
var hsVars = {
    ticks: 1606167984874,
    page_id: 0,

    content_group_id: 0,
    portal_id: 6968579,
    app_hs_base_url: "https://app.hubspot.com",
    cp_hs_base_url: "https://cp.hubspot.com",
    language: "en",
    analytics_page_type: "standard-page",
    category_id: 1,
    folder_id: 0,
    is_hubspot_user: false
}
</script>

<script defer src="/hs/hsstatic/HubspotToolsMenu/static-1.79/js/index.js"></script>

    

</body></html> ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at FSharp.Data.HttpHelpers.getResponseAsync@1319-4.Invoke(Exception _arg2)
   at <StartupCode$FSharp-Core>.$Async.TryWith@1113-1.Invoke(Exception exn)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt, FSharpFunc`2 catchFilter, ExceptionDispatchInfo edi)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
   --- End of inner exception stack trace ---
   at FSharp.Data.HttpHelpers.augmentWebExceptionsWithDetails@1227-3.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@607.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.AsyncResult`1.Commit()
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Program.main@132-1.Invoke(HtmlNode w)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at Program.main@124.Invoke(String level)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map@1324-3.Invoke(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map[T,TResult](FSharpFunc`2 mapping, T[] array)
   at Program.main(String[] argv)
</p></details>

**Comment by kerams** [comment]
Thanks, I'll take a look tomorrow.

**Comment by kerams** [comment]
I have bad news. Memrise has removed the way to retrieve detailed information about a particular word that the scraper used. The data is still obviously available elsewhere in a different format, but it requires the user to start a session, therefore you need to be logged in, meaning you'd need to supply the session cookie from your browser to the scraper. In any case this is not a quick fix and for the time being the scraper will be unusable. Sorry about that.

**Comment by firenze998** [comment]
I took a closer look at the error, and if the scraper uses this link to retrieve information: https://www.memrise.com/api/thing/get?thing_id=41265960, I think memrise changed it to
https://app.memrise.com/api/thing/get/?thing_id=41265960

**Comment by kerams** [comment]
*facepalm*, you're right, I completely overlooked that. Let me fix it then :).

**Comment by kerams** [comment]
[The latest version](https://github.com/kerams/memrise-scraper/releases/tag/v1.0.4) should work, I've tried it on your course.

**Comment by firenze998** [comment]
Yes, it works now. Thank you!

**Comment by kerams** [comment]
Don't mention it.
